# Generated by Django 3.2.8 on 2021-10-28 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.BigAutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=20, unique=True, verbose_name='Alias')),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.IntegerField(default=0)),
                ('peso', models.IntegerField(default=0)),
                ('posicion', models.CharField(choices=[('AR', 'Arquero'), ('LA', 'Lateral'), ('CA', 'Carrilero'), ('DF', 'Defensa Central'), ('VR', 'Volante de Recuperacion'), ('VC', 'Volante de Creacion'), ('VO', 'Volante Ofensivo'), ('DE', 'Delantero')], default='DE', max_length=2)),
                ('rating_jugador', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_jugador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=20)),
                ('cantidad_jugadores', models.IntegerField(default=0)),
                ('rating_equipo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('localidad', models.CharField(choices=[('T', 'Tunjuelito'), ('K', 'Kennedy'), ('E', 'Engativa'), ('M', 'Martires')], default='T', max_length=1)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id_convocatoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_convocatoria', models.DateTimeField()),
                ('posicion_requerida', models.CharField(choices=[('AR', 'Arquero'), ('LA', 'Lateral'), ('CA', 'Carrilero'), ('DF', 'Defensa Central'), ('VR', 'Volante de Recuperacion'), ('VC', 'Volante de Creacion'), ('VO', 'Volante Ofensivo'), ('DE', 'Delantero')], default='DE', max_length=2)),
                ('nombre_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_equipo_solicita', to='futbolTinderApp.equipo')),
            ],
        ),
    ]
