# Generated by Django 3.2.7 on 2021-11-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolTinderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Convocatoria',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
